# Generated by Django 3.0.4 on 2020-04-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='time',
            field=models.CharField(default='00:00', max_length=6),
        ),
    ]
