# Generated by Django 3.0.4 on 2020-03-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('info', models.TextField()),
                ('description', models.TextField()),
                ('start_data', models.DateTimeField()),
                ('end_data', models.DateTimeField()),
                ('done', models.BooleanField()),
            ],
        ),
    ]
