# Generated by Django 3.0.4 on 2020-03-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200325_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_data',
            field=models.DateField(),
        ),
    ]
