# Generated by Django 3.0.4 on 2020-03-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200326_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_data',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='info',
            field=models.CharField(max_length=100),
        ),
    ]
