# Generated by Django 3.0.4 on 2020-03-31 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='tasks.Brand'),
            preserve_default=False,
        ),
    ]
