# Generated by Django 3.0.4 on 2020-04-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_dailytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='tag',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
