# Generated by Django 3.0.4 on 2020-04-02 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0014_dailytask_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_daily', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
