# Generated by Django 3.0.4 on 2020-04-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_dailytask_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='completed',
            field=models.IntegerField(default=0),
        ),
    ]
