# Generated by Django 3.0.4 on 2020-05-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_auto_20200409_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='info',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
