# Generated by Django 3.0.4 on 2020-05-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_auto_20200503_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytask',
            name='tag',
        ),
    ]
